language: python
cache: pip
sudo: false
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy3"
install:
  - pip install codecov pytest-cov
matrix:
  include:
    - python: "3.7"
      sudo: required
      dist: xenial
    - python: "nightly"
      sudo: required
      dist: xenial
  allow_failures:
    - python: "pypy3"
    - python: "nightly"
script:
  - pip install -e ".[testing]"
  # `BOTO_CONFIG=` prevent travis from editing the boto3 configuration and thus crashing;
  #  see https://github.com/spulec/moto/issues/1771
  - BOTO_CONFIG=/dev/null pytest --cov --cov-report=
after_success:
  - codecov
